import { Request, Response } from "express";
import { HourlyWeather } from "../../../types/types";

export function hourlyForecastHandler(
  req: Request,
  res: Response<HourlyWeather[]>
) {
  return res.status(200).json([
    {
      time: "2PM",
      condition: "Sunny",
      location: "Melbourne",
      lowestTemperature: "8°",
      highestTemperature: "20°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "3PM",
      condition: "Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "24°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "4PM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "11°",
      highestTemperature: "26°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "5PM",
      condition: "Sunny",
      location: "Melbourne",
      lowestTemperature: "15°",
      highestTemperature: "28°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "6PM",
      condition: "Cloudy",
      location: "Melbourne",
      lowestTemperature: "15°",
      highestTemperature: "27°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "7PM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "13°",
      highestTemperature: "25°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "8PM",
      condition: "Sunny",
      location: "Melbourne",
      lowestTemperature: "12°",
      highestTemperature: "30°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "11PM",
      condition: "Cloudy",
      location: "Melbourne",
      lowestTemperature: "12°",
      highestTemperature: "29°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "12PM",
      condition: "Sunny",
      location: "Melbourne",
      lowestTemperature: "9°",
      highestTemperature: "17°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "1AM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "2AM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "3AM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "4AM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "5AM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "6AM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "7AM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "8AM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "9AM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "10AM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "11AM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "12AM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "1PM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
    {
      time: "2PM",
      condition: "Cloudy and Sunny",
      location: "Melbourne",
      lowestTemperature: "7°",
      highestTemperature: "19°",
      temperature: "20°",
      temperatureDescription: "partly cloudy",
    },
  ]);
}
